version: '3.8'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: visor-mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=VisorStrongPass123!
    ports:
      - "1433:1433"
    volumes:
      - ./init-mssql.sql:/docker-entrypoint-initdb.d/init.sql # <-- Было init.sql

  postgres:
    image: postgres:16
    container_name: visor-postgres
    environment:
      POSTGRES_PASSWORD: VisorStrongPass123!
      POSTGRES_DB: VisorTestDb
    ports:
      - "5432:5432"
    volumes:
      - ./init-pg.sql:/docker-entrypoint-initdb.d/init.sql